const ContentRatingSystem = {
  "type": "string",
  "description": "Content rating system\n\n`BBFC` `OFLC` `OFLCNZ` `DJCTQ` `MDA` `MPAA` `CHVRS` `RCQ` `IFCO` `FSK` `NICAM` `MCCYP` `EIRIN` `HK` `CBFC` `NMHH` `VRC` `RSAC` `ESRB` `ELSPA` `PEGI` `USK` `SELL` `ADESE` `GSRR` `ITUNES`",
  "enum": [
    "BBFC",
    "OFLC",
    "OFLCNZ",
    "DJCTQ",
    "MDA",
    "MPAA",
    "CHVRS",
    "RCQ",
    "IFCO",
    "FSK",
    "NICAM",
    "MCCYP",
    "EIRIN",
    "HK",
    "CBFC",
    "NMHH",
    "VRC",
    "RSAC",
    "ESRB",
    "ELSPA",
    "PEGI",
    "USK",
    "SELL",
    "ADESE",
    "GSRR",
    "ITUNES"
  ],
  "title": "ContentRatingSystem",
  "x-readme-ref-name": "ContentRatingSystem"
} as const;
export default ContentRatingSystem
