name: Sync `docs` directory to ReadMe

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3

      - name: Sync docs to ReadMe
        uses: readmeio/rdme@7.3.0
        with:
          rdme: docs ./docs --key=${{ secrets.README_API_KEY }} --version=1.0
