name: Sync `docs` directory to ReadMe

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3

      - name: Install deps
        run: npm ci

      - name: Build docs
        run: npm run build-docs

      - name: Sync docs to ReadMe
        uses: readmeio/rdme@8.0.0
        with:
          rdme: docs ./dist/docs --key=${{ secrets.README_API_KEY }} --version=1.0
